# https://probot.github.io/apps/settings/
# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
# See https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator for available options
# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
# https://docs.github.com/en/rest/reference/repos#update-branch-protection

branches:
  - name: 'master'
    protection:
      enforce_admins: true
      required_linear_history: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        dismissal_restrictions:
          users: ['jessefarinacci']
          teams: []
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      restrictions:
        apps: []
        users: ['jessefarinacci']
        teams: []

collaborators:
   - username: 'jessefarinacci'
     permission: 'admin'

labels:
  - name: 'bug'
    color: '#CC0000'
    description: 'request bug fix'
  - name: 'feature'
    color: '#336699'
    description: 'request feature'

repository:
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true
  default_branch: 'master'
  delete_branch_on_merge: true
  description: 'GitHub Settings'
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  homepage: 'https://github.com/jessefarinacci'
  name: '.github'
  private: false
  topics: 'github, settings'
  visibility: public
